### ISSUE TITLE
node_modules is created as root:root

### ISSUE THREAD

**Issue by sorenjohanson** [kitsteam/stop-motion-app#209]
With a fresh clone of the repository and when executing `docker compose up -d` for the first time, `node_modules` seems to be created with `root:root` permissions. This prevents `yarn install` from executing successfully as it's run with the `node` user.

Not sure if this is a local issue, but once `node_modules` is created in the local file system, it's possible to work around the issue by setting the correct permissions locally (in my case, `cert:cert`) and forcibly re-creating the Docker container using `docker compose up -d --build --force-recreate`. The `node_modules` folder is then created/copied with the correct permissions.

**Comment by sorenjohanson** [comment]
This is most likely caused by (accidentally) overwriting node_modules created by the Dockerfile in `docker-compose.yml`:

```
volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules:cached
 ```

**Comment by JannikStreek** [comment]
Hm I just cloned the repo and everything works out of the box. The folder is created with `node node` permissions, but I actually had to execute `yarn install` myself. Can you elaborate what your problem was and how I can reproduce it?
